### ISSUE TITLE
Warden Loot mod from Forge with otifine not working

### ISSUE THREAD

**Issue by deadsupery** [nu11une/wardenloot#7]
Hello when I enter the dependencies of the mod and the mod with Optifine (OptiFine HD U H8) minecraft freezes on the Mojand screen without crashing but it does not enter. In Warden Loot [Forge] mod. 
(It's the same problem with my Minecraft but I wanted to confirm it)

**Comment by nu11une** [comment]
Looks like there's a problem between Optifine and the MoreMcmeta dependency. I'll forward the issue to MoreMcmeta, but since Optifine is closed source, there's a good chance it will not be fixed. I've also made a new release (1.0.9-1.19.x) for Warden Loot that makes the MoreMcmeta dependency optional so you can disable it.

**Comment by deadsupery** [comment]
Okay thanks. You can now close the thread if you want or wait until they fix MoreMcmeta

**Comment by nu11une** [comment]
this should be fixed with [MoreMcmeta v1.19-3.0.5](https://www.curseforge.com/minecraft/mc-mods/moremcmeta/files/3879265)
